- terminus/builders/simple_city_builder.py
- terminus/models/block.py
- terminus/models/building.py
- terminus/models/city.py
- terminus/models/city_model.py
- terminus/models/ground_plane.py
- terminus/models/road.py
- terminus/models/simple_city_builder.py
- terminus/run_generator.py
Minor arrangement to parameters and module organization
> Code cleanup

- terminus/builders/simple_city_builder.py
- terminus/models/building.py
This addresses issue #6.
@basicNew ptal
> Parametrize building parameters.

- README.md
- terminus/builders/__init__.py
- terminus/builders/procedural_city/vertex.py
- terminus/builders/procedural_city_builder.py
- terminus/builders/simple_city_builder.py
- terminus/models/block.py
- terminus/models/building.py
- terminus/models/city.py
- terminus/models/city_element.py
- terminus/models/city_model.py
- terminus/models/point.py
- terminus/models/road.py
- terminus/run_generator.py
Fixes #7
Just a basic kick-off to have a builder that reads the roadmap file created by https://github.com/josauder/procedural_city_generation and generates the road layout in our model.
> Build streets from procedural city generation

- terminus/builders/simple_city_builder.py
Addresses issue #16.
Adds diagonal streets to our `SimpleCityBuilder`
Screenshots:
> Add diagonal streets to our simple city.

- docker/Makefile
- docker/README.md
- docker/gazebo7-intel/Dockerfile
- docker/gazebo7-nvidia/Dockerfile
- docker/gazebo7/Dockerfile
- docker/run_simulator
Address issue #29 
Please @ernestmc check this PR
> Add docker files for gazebo compilation

- terminus/builders/procedural_city/vertex_graph_to_roads_converter.py
- terminus/builders/procedural_city_builder.py
- terminus/builders/simple_city_builder.py
- terminus/generators/file_generator.py
- terminus/generators/rndf_generator.py
- terminus/generators/sdf_generator.py
- terminus/models/block.py
- terminus/models/building.py
- terminus/models/city.py
- terminus/models/city_element.py
- terminus/models/city_model.py
- terminus/models/ground_plane.py
- terminus/models/road.py
- terminus/models/street.py
- terminus/models/trunk.py
- terminus/run_generator.py
- terminus/tests/vertex_graph_to_roads_converter_test.py
Fixes #31 
In this PR:
- Changed code to have a generator per format we need
- Generate both sdf and rndf files when running the generator
- [Minor] Change default sdf file name
> Support RNDF file generation. 

- .travis.yml
- README.md
This fixes #27 and #15.
Once this is merged I will enable travis integration for the repo.
> Setup travis CI for this repo

- terminus/builders/procedural_city_builder.py
- terminus/generators/file_generator.py
- terminus/generators/rndf_generator.py
- terminus/generators/sdf_generator.py
- terminus/models/road.py
- terminus/run_generator.py
- General refactors
- Fixed (lat,lon) transformation and RNDF generation
Sample RNDF output for the 10km² sample
> Tweak RNDF generation

- README.md
- terminus/generators/rndf_generator.py
Just a couple of small fixes.
@garyservin PTAL
> Minor fixes

- terminus/tests/rndf_generator_test.py
Add test cases for road junctions:
- L junction
- Y junction: one to many and many to one:
> Add tests for RNDF junctions

- docker/Makefile
- docker/gazebo7/Dockerfile
- docker/run_simulator
This dockerfile modification includes [Manifold](https://bitbucket.org/osrf/manifold) dependencies, downloads and compiles Manifold repository and includes [rndf_gazebo_plugin](https://bitbucket.org/JChoclin/rndf_gazebo_plugin) repository.
> Issue/#77 Docker image improvements

- README.md
Connects to #102
Tested installation from scratch on a docker with Ubuntu 14.04. Added some missing dependencies and some fixes.
> Fix python deps

- docker/README.md
The following was included:
- Note on volumes 
- Note on Gazebo and Manifold arguments for the commits.
- Include other repository dependencies.
> #117 Updated README.md of Docker

- terminus/builders/osm_city_builder.py
- terminus/models/road.py
Fixes #106 
@basicNew can you review when you have some spare time, thanks!
> OSM: Add junctions

- README.md
> Update README to add OSM builder

- .travis.yml
- README.md
- setup.py
Tested with a clean docker container and followed the README. Fixes #115
> Fix dependencies for running pcg builder

- terminus/builders/osm_city_builder.py
- terminus/builders/simple_city_builder.py
- terminus/generators/sdf_generator.py
- terminus/models/building.py
Connects to #120
Update `OsmCityBuilder` for reading building information into the city model.
Screenshot:
> Load building information from OSM.

- terminus/builders/osm_city_builder.py
- terminus/models/road.py
Fixes #105 
@basicNew I've added the call to `be_two_way()` as you've mentioned. How should we handle that method?
> Make sure one way streets are OK and make two way roads

- terminus/builders/osm_city_builder.py
Moved junctions loop outside of the main loop for ways and make sure to only use ways (not buildings) for junctions.
Fixes #135
> Fix junctions generation for OSM builder

- terminus/run_generator.py
Fixes #41
Now you get something like:
```
$ python terminus/run_generator.py --builder=OsmCityBuilder --parameters osm_map=samples/osm_sample/osrf.osm --debug
Building city using OsmCityBuilder
Generating Gazebo 7 SDF
Generating Gazebo 8 SDF
Generating street plot
Generating RNDF file
```
> Add minimal feedback

- terminus/builders/osm_city_builder.py
- terminus/generators/rndf_generator.py
- terminus/generators/sdf_generator_gazebo_8.py
- terminus/geometry/latlon.py
- terminus/run_generator.py
- terminus/tests/latlon_test.py
- terminus/tests/rndf_generator_test.py
Fixes #131 
- Add `LatLon` class, including conversions to/from cartesian coordinates.
- Remove existing duplicated conversion code.
> Add lat lon class

- terminus/builders/osm_city_builder.py
- terminus/geometry/line_segment.py
- terminus/geometry/point.py
- terminus/tests/line_segment_test.py
I've tested it with the same osm file and seems to work
Fixes #148
> osm_city_builder: Make sure to clip longer streets to the bounding box

- terminus/builders/osm_city_builder.py
- terminus/geometry/latlon.py
- terminus/geometry/point.py
- terminus/tests/latlon_test.py
Two methods were added to the LatLon class:
- middle_point
- is_inside
The code in osm_city_builder.py was modified using the LatLon class
> Simpify city builder with lat lon

- terminus/generators/monolane_id_mapper.py
This fixes an issue where the connection names were not being rendered correctly into the monolane files.
> fix rendering of connection names

- terminus/city_generation_process.py
- terminus/models/city.py
- terminus/models/city_statistics.py
- terminus/models/lane_intersection_node.py
- terminus/models/lane_node.py
- terminus/models/lane_simple_node.py
- terminus/tests/city_statistics_test.py
- terminus/tests/test_cities_generator.py
Fixes #213
Sample outputs:
```
$ python terminus/run_generator.py --builder=SimpleCityBuilder --debug
Building city using SimpleCityBuilder
====================================
Statistics for city_1
====================================
Roads: 12
Intersections: 25
Lanes: 12
Total lane nodes: 60
Total lane intersections: 60
Average lane nodes: 5.0
Average lane intersections: 5.0
Buildings: 120
Blocks: 24
====================================
```
```
$ python terminus/run_generator.py --builder=OsmCityBuilder --parameters osm_map=samples/mcity/osm_derived/mcity.osm --debug
Building city using OsmCityBuilder
====================================
Statistics for city_1
====================================
Roads: 33
Intersections: 46
Lanes: 33
Total lane nodes: 291
Total lane intersections: 100 …
```
> Add model stats

- terminus/tests/monolane_generator_test.py
- terminus/tests/monolane_generator_test_old.py
- terminus/tests/rndf_generator_test.py
- terminus/tests/test_cities_generator.py
Fixes #224 
Use the same tests examples in both RNDF and monolane generator
> Normalize generator tests

- terminus/geometry/arc.py
- terminus/geometry/point.py
- terminus/models/lines_and_arcs_builder.py
- terminus/models/road.py
- terminus/tests/point_test.py
Modifies angle implementation in Point to make it return angle in degrees between -180 and 180
> Modified angle implementation in Point

- terminus/builders/osm_city_builder.py
- terminus/geometry/line_segment.py
- terminus/models/lane.py
- terminus/models/path_geometry.py
- terminus/models/path_geometry_builder.py
- terminus/models/waypoint_geometry.py
- terminus/tests/line_segment_test.py
- terminus/tests/lines_and_arcs_path_geometry_test.py
- terminus/tests/monolane_generator_test.py
- terminus/tests/polyline_builder_test.py
- terminus/tests/rndf_generator_test.py
- terminus/tests/test_cities_generator.py
Fixes #234
Also address some issues with floating point math error and bug on OSM builder after intersections were normalized to return a list.
Now the roads are properly connected:
> Fix missing connection road ends in arc

- terminus/city_generation_process.py
- terminus/generators/street_plot_generator.py
- terminus/geometry/arc.py
- terminus/geometry/line_segment.py
- terminus/models/path_geometry.py
- terminus/tests/polyline_builder_test.py
Fixes the implementation part of #236
> Added street plot generation back

- run_tests.sh
- terminus/builders/osm_city_builder.py
- terminus/generators/monolane_generator.py
- terminus/geometry/arc.py
- terminus/geometry/bounding_box.py
- terminus/geometry/line_segment.py
- terminus/geometry/point.py
- terminus/models/path_geometry.py
- terminus/models/path_geometry_builder.py
- terminus/models/waypoint.py
- terminus/models/waypoint_geometry.py
- terminus/tests/monolane_generator_test.py
- terminus/tests/rndf_generator_test.py
- Fixes some issues with float arithmetic precision
- Changes how we compute intersections connections, starting from a smaller arc size and looping until the  ending point is a perfect match with the entry lane.
- Changed how logging is handled. Will change again soon to be less verbose.
- Changed test runner to log only errors.
> Misc fixes

- terminus/geometry/arc.py
- terminus/geometry/circle.py
- terminus/geometry/point.py
- terminus/tests/arc_test.py
- terminus/tests/circle_test.py
- terminus/tests/custom_assertions_mixin.py
Many tests were added to arc_test.py.
I also added two methods to arc class: counter_clockwise and from_points_in_circle.
I modified _find_arc_intersection to consider arcs contained in the same circle, and modified includes_point too.
To circle class I added from_points_and_radius method.
To point class I added orthonormal_vector and mid_point methods.
> Make arc tests

- terminus/builders/procedural_city_builder.py
- terminus/generators/monolane_generator.py
- terminus/models/junction_builder.py
- terminus/tests/monolane_generator_test.py
- Fixes #247 
- Makes tests less fragile
> Trim extra segments

- terminus/city_generation_process.py
- terminus/generators/abstract_sdf_generator.py
> Restore SDF generators and add licence when present

- terminus/builders/simple_city_builder.py
- terminus/generators/rndf_generator.py
- terminus/tests/rndf_generator_test.py
> Sanitize RNDF strings

- terminus/geometry/line.py
- terminus/geometry/line_segment.py
- terminus/models/lane.py
- terminus/models/lines_and_arcs_geometry.py
- terminus/tests/monolane_generator_test.py
- terminus/tests/rndf_generator_test.py
- terminus/tests/test_cities_generator.py
Fixes #256 by considering the case of collinear lanes with different offsets
> Fix collinear connections

- run_pep8.sh
- terminus/geometry/line.py
- terminus/tests/monolane_generator_test.py
Fix `perpendicular_line_at` implementation so it can handle lines with undefined slope (vertical lines)
> Fix slope bug
